### ISSUE TITLE
Update to latest nexus version

### ISSUE THREAD

**Issue by gabereiser** [shekhargulati/nexus#3]
Can this be updated to reflect the latest nexus version so we don't have to spin our wheels in doing it by hand, thus duplicating this effort?

**Comment by juliogonzalez** [comment]
@gabereiser, PR #4 should do the trick.

However current project depends on nexus.war and it seems that it won't be supported soon: https://support.sonatype.com/hc/en-us/articles/213465668-Where-is-the-Nexus-OSS-war-file-

Nexus 3.X is not available yet, but soon we'll need to research if we can use the jetty bundle instead of tomcat and the war.
